### ISSUE TITLE
Misc links

### ISSUE THREAD

**Issue by Carreau** [njsmith/sempervirens#13]
https://www.tacc.utexas.edu/research-development/tacc-projects/xalt
https://github.com/Fahey-McLay/xalt

The manual have some design decision on how to store user data:

https://github.com/Fahey-McLay/xalt/blob/master/doc/XALTDesignandInstallationManual-0.5.pdf

**Comment by njsmith** [comment]
I added these to the [wiki](https://github.com/njsmith/sempervirens/wiki), which seems like a good place for them.
